### ISSUE TITLE
Does not linkify extension-less files

### ISSUE THREAD

**Issue by josephfrazier** [OctoLinker/browser-extension#106]
For example, lines 2 and 3 of this blob should have links, but they don't, since the blob name has no extension: https://github.com/localtunnel/localtunnel/blob/9a1d48764a167ae9fb05f42efdd7de0005e9edfc/bin/client

Perhaps we should add a way to detect filetype based on the blob's [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix))? In the above example, `#!/usr/bin/env node` indicates that the file should be interpreted as javascript.

**Comment by stefanbuck** [comment]
Right, there is some space for improvements. I like the idea of guessing the filetype by looking at the blob type. 

Similar to https://github.com/OctoLinker/browser-extension/issues/56
