### ISSUE TITLE
Submit to Opera addons site

### ISSUE THREAD

**Issue by shwetank** [OctoLinker/browser-extension#116]
It would be great for users using Opera to also have this extension from the [official addons site](https://addons.opera.com). 

Chrome extensions are compatible with Opera, and even supports the .crx file format used by chrome. It just needs to be submitted to the site.

**Comment by stefanbuck** [comment]
Oh nice I didn't know that. Will try upload a version this weekend.

**Comment by stefanbuck** [comment]
🎉  https://addons.opera.com/en/extensions/details/octolinker/
