### ISSUE TITLE
show double import

### ISSUE THREAD

**Issue by ubuntugx** [OctoLinker/browser-extension#117]
![image](https://cloud.githubusercontent.com/assets/8335135/16537803/76f491d6-4040-11e6-9fc4-49b90d8070a3.png)
link: https://github.com/weui/react-weui/blob/master/src/components/cell/cell.js
can go to correct link, but will add additional 'import'.

**Comment by stefanbuck** [comment]
Works fine for me. Do you have any other extensions installed? Disable them one by one to see which conflicts with the OctoLinker.

**Comment by ubuntugx** [comment]
@stefanbuck you are right, thank you. OctoLinker conflicts with Sourcegraph for GitHub(https://chrome.google.com/webstore/detail/sourcegraph-for-github/dgjhfomjieaadpoljlnidmbgkdffpack)
when I disabled Sourcegraph for GitHub, the bug disappear.

**Comment by stefanbuck** [comment]
The extension wraps the same elements like I do. So I think this can't be solve in the near feature.
