### ISSUE TITLE
Release notes 4.2.0

### ISSUE THREAD

**Issue by stefanbuck** [OctoLinker/browser-extension#135]
FYI @josephfrazier 

---

## Highlights
- Publish Firefox version of the OctoLinker #100
- Publish Opera version of the OctoLinker #118
- Add TypeScript support. This will let you click on `import` and `require` statements in TypeScript files. Furthermore reference tags like `<reference path="./foo.d.ts" />` are clickable as well #130

## Other Changes

- Link files from packages `foo/bar.js` #95
- Link files from scope packages `@foo/bar/baz.js` #115
- Link the `bin` field in `package.json` #127
- Link the `browser` field in `package.json` #126
- Support the `dependencies` and `conflicts` filed for Homebrew-Cask #124
- Open OctoLinker notification in new tab #85.
- Add close button to OctoLinker notificaton #102
- Fix conflict with [github-highlight-selected](https://github.com/Nuclides/github-highlight-selected) chrome extension #88
- Allow links to be "clicked" with [Vimium](https://vimium.github.io/) chrome extension #114

## All Changes

[v4.1.0...v4.2.0](https://github.com/OctoLinker/browser-extension/compare/v4.1.0...v4.2.0)

---

Huge thanks to @josephfrazier @dpeukert @dannyfritz @ruanyl

**Comment by stefanbuck** [comment]
@josephfrazier please make sure that the release notes are updated https://github.com/OctoLinker/browser-extension/releases/tag/v4.2.0 Thanks

**Comment by stefanbuck** [comment]
Sorry for the back and forth from my side, but I updated the notes by myself just now. The publish process was super fast this time and the notes should be in place.

**Comment by stefanbuck** [comment]
Thanks @josephfrazier for doing this release. Will send a tweet out on Monday

**Comment by josephfrazier** [comment]
Sorry for all the confusion (and thanks for fixing the release notes)! Now that we've gotten things sorted out, I think future releases will go much more smoothly. I might try to summarize the release steps somewhere (wiki, CONTRIBUTING.md, etc) for reference later.

**Comment by stefanbuck** [comment]
No worries, at the end all went well.
