### ISSUE TITLE
#141 broke npm links

### ISSUE THREAD

**Issue by josephfrazier** [OctoLinker/browser-extension#144]
To reproduce this problem, build the extension from c767c53fed299ded2858f8c9c792c8c5cbc5111a and use it to click on `babel-polyfill` at https://github.com/OctoLinker/browser-extension/blob/730815cc3656b3c96bf4435f97c5ae7eff28a3cb/lib/app.js#L1

There's a TypeError [here](https://github.com/OctoLinker/browser-extension/commit/c767c53fed299ded2858f8c9c792c8c5cbc5111a#diff-34a0c3d0e732cfd9a779519a0ed4c7b0R52) because the function expects to receive a String, but receives a `{url, method}`.

I could probably just fix this myself, but I'm thinking we should probably add some more testing in to make sure this sort of thing can't happen again. @stefanbuck, what do you think?

**Comment by stefanbuck** [comment]
Ohh no. Yes, pleases I'm looking forward to see your fix
