### ISSUE TITLE
Support .NET Core Project.json

### ISSUE THREAD

**Issue by rprouse** [OctoLinker/browser-extension#163]
The project.json file for .NET Core projects lists dependencies much like NPM. These dependencies tend to link to NuGet.org, but if a nuget.config file is present, it may add or change the package source. I would propose only using NuGet.org as the primary package source since finding the nuget.config file could be problematic.

The reference for project.json is at https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json

An example project.json file is,

```json
{
    "version": "1.1.0-*",

    "dependencies": {
        "NUnitWithDotNetCoreRC2": {
            "target": "project"
        },
        "NUnit": "3.4.0",
        "dotnet-test-nunit": "3.4.0-beta-2"
    },
    "testRunner": "nunit",

    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "netcoreapp1.0",
                "portable-net45+win8"
            ],
            "dependencies": {
                "Microsoft.NETCore.App": {
                    "version": "1.0.0-*",
                    "type": "platform"
                }
            }
        }
    }
}
```

The nodes of interest are the `dependencies`. Those with `"target": "project"` link to other projects in the current solution/repository and should not be followed.

The link target could be in the form https://www.nuget.org/packages/{PACKAGE}/{VERSION}, for example https://www.nuget.org/packages/dotnet-test-nunit/3.4.0-beta-2

**Comment by stefanbuck** [comment]
Thanks for the detailed description. Would you like to contribute that feature with some guidance and support from our side? If not, no worries I'll put it to our todo list and we will pick it up at some point.

**Comment by rprouse** [comment]
I will take it if I find some time, but I am pretty busy with other projects right now. If someone else wants to pick this up, feel free. I will post a comment if I start on it.

**Comment by Ibrahim-Islam** [comment]
I will start on this

**Comment by josephfrazier** [comment]
Thanks, @Ibrahim-Islam! Let me know if you have any questions.

**Comment by Ibrahim-Islam** [comment]
@josephfrazier I am having some trouble building the project. Can you explain what this [line](https://github.com/OctoLinker/browser-extension/blob/master/package.json#L17) is doing?

**Comment by stefanbuck** [comment]
The `assets/manifest.json` contains values which are Firefox specific. In order to produce a valid `manifest.json` for Chrome this line removes the `applications` value and creates a copy in `/dist/`. 

What issues do you have with building the project? Did you use `npm run chrome-build` to build the extension?

**Comment by Ibrahim-Islam** [comment]
@stefanbuck Yes. I followed the contributing doc and tried to build according to it. Following is the error I get and I am on Windows.

```
> npm run chrome-manifest && webpack

> OctoLinker@4.4.0 chrome-manifest C:\Users\Ibrahim\Desktop\git\browser-extension
> mkdir -p dist && json -e 'delete this.applications; this.permissions.shift()' < assets/manifest.json > dist/manifest.json

' was unexpected at this time.
```

**Comment by stefanbuck** [comment]
Looks like the single quote isn't escaped correctly on windows. Can you change the single quote sign to an escaped double quote sign please.


```diff
-  "chrome-manifest": "mkdir -p dist && json -e 'delete this.applications; this.permissions.shift()' < assets/manifest.json > dist/manifest.json",
+ "chrome-manifest": "mkdir -p dist && json -e \"delete this.applications; this.permissions.shift()\" < assets/manifest.json > dist/manifest.json",
```

**Comment by Ibrahim-Islam** [comment]
@stefanbuck Thanks. That worked and also had to remove `-p` from `mkdir -p dist` windows does not seem to have a flag `-p` for `mkdir` command.

**Comment by josephfrazier** [comment]
Oh yeah, I guess the build scripts weren't really set up to work on Windows... I've pulled in the double quote fix and proposed a fix for the `mkdir -p` issue as well.

Maybe we should consider running CI on Windows ([AppVeyor](https://www.appveyor.com/) is good for this) and adding `npm run package-all` to the test script. What do you think, @stefanbuck?

**Comment by Ibrahim-Islam** [comment]
@stefanbuck @josephfrazier  In the following I will describe the current status and some things I can use help with.

I was able to get it working given the following `project.json`:
```
{
  "buildOptions": {
    "emitEntryPoint": true,
    "debugType": "portable"
  },
  "dependencies" : {
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0"
  },
  "frameworks": {
    "net451": { }
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview2-final"
    }
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }
}
```
But in the following case, there will be an error `Uncaught TypeError: Argument 1 should be a string.` from `escapeRegexString` due to `Microsoft.NETCore.App` package because version placeholder can be an [object](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json#dependencies) also but packages defined above it will redirect as expected:
```
  "dependencies": {
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    }
  }
```
But in following case none of the packages will be linked due to the exception mentioned above:
```
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0"
  }
```

Also package versions can be written like following:
```
  "dependencies": {
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0-*",
    "Microsoft.AspNetCore.Authentication.Facebook": "1.1.0-*"
  }
```
Which version to redirect to in this case or just redirecting to the nuget package will suffice minus the version?

**Comment by josephfrazier** [comment]
@Ibrahim-Islam Nice progress! I'd love to help out, but could you first push your work up to a branch and make a pull request? I think it'll be easier to collaborate when the code is readily available.

**Comment by stefanbuck** [comment]
@Ibrahim-Islam implement this #190 🎉
