### ISSUE TITLE
Add options page

### ISSUE THREAD

**Issue by stefanbuck** [OctoLinker/browser-extension#170]
This issue is a subtask in order to implement #75. If you are starting to work on this issue, please leave comment so others are aware of it. Thank you!

In order to implement features such as #75 we need an option page where a user can enter a custom GitHub Enterprise url. This issue should focus only on implementing an empty page which is accessible in all supported browsers (Chrome, Firefox and Opera).

**Comment by josephfrazier** [comment]
Here are some relevant browser documentation pages:

* [Chrome](https://developer.chrome.com/extensions/optionsV2)
* [Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#Options_pages)
