### ISSUE TITLE
Not installable on Firefox 45.

### ISSUE THREAD

**Issue by Spudley** [OctoLinker/browser-extension#177]
Hi.

I just wanted to report that I tried installing this extension on Firefox, but the Mozilla store reports that it isn't compatible with FF 45.

Any chance of fixing this, please? As the extension sounds really useful.

Thanks.

**Comment by stefanbuck** [comment]
The extension uses the new webextensions api which was added in [Firefox 48](https://blog.mozilla.org/addons/2016/04/29/webextensions-in-firefox-48/). Therefore it will never work in FF < 48. What prevents you from upgrading your browser to 48?

**Comment by Spudley** [comment]
FF45 is the current Extended Support Release (ESR) so many corporate users will be on this version for some time (until the end of this year anyway). Guess I'll have to wait.

In the meanwhile, my copy of Chrome isn't version locked, so I'll try out the extension on that instead for now.

I've also got a question about whether you'll be porting the extension to Edge, but I'll post that as a separate ticket.  :)
