### ISSUE TITLE
Error in console on GitHub PR page

### ISSUE THREAD

**Issue by SpaceK33z** [OctoLinker/browser-extension#184]
When I go to a PR page, for example [this one](https://github.com/sindresorhus/refined-github/pull/282), I see this in my console:

```
octo-linker.js:28 Uncaught TypeError: Cannot read property 'classList' of undefined
```

**Comment by stefanbuck** [comment]
Thanks for the report. We'll take a look at it as soon as possible!

**Comment by stefanbuck** [comment]
Fixed
