### ISSUE TITLE
Add option to set default click behaviour (same tab/new tab) 

### ISSUE THREAD

**Issue by stefanbuck** [OctoLinker/browser-extension#185]
Many users were asking for the option of being able to set the default click behaviour. With the recently added option page #178 it should be quite simple. @josephfrazier already explored how to persist the settings. Please check out his PR for the details #182.

**Comment by bfred-it** [comment]
I've been wondering if the lookup could be done differently to allow this specific behavior (and perhaps speed up the whole process with direct links)

Some imports, like `require('../file.js')` can be simple links to that file on GitHub. If they're not found, GitHub will show a 404.

Imports from npm can use ghub.io links, e.g. <code>require('[image-promise](http://ghub.io/image-promise)')</code>

Alternatively, a generic solution would be to use simple links to an interstitial page under `chrome-extension://jlmafbaeoofdegohdhinkhilhclaklkp/` that waits for the resolution and then redirects.

There might be a way to even have the browser cache the 301 redirects, perhaps through service workers.

**Comment by josephfrazier** [comment]
There's some discussion about the idea of direct links in https://github.com/OctoLinker/browser-extension/pull/87

> Some imports, like `require('../file.js')` can be simple links to that file on GitHub. If they're not found, GitHub will show a 404.

Technically, `require('../file.js')` could refer to `../file.js/index.js`, but that's presumably a very small edge case at most.

**Comment by stefanbuck** [comment]
Implemented see #216
