### ISSUE TITLE
Incorrect display of commented-out code

### ISSUE THREAD

**Issue by xwartz** [OctoLinker/browser-extension#191]
![image](https://cloud.githubusercontent.com/assets/4149827/19309804/adadf1f8-90b9-11e6-969c-0b85c332ae2a.png)

Live example https://github.com/xwartz/robot/blob/master/src/avatar.js

**Comment by josephfrazier** [comment]
Thanks for the report, @xwartz! I've got a fix pending at https://github.com/OctoLinker/browser-extension/pull/192

**Comment by stefanbuck** [comment]
@xwartz will be fixed in the next release. Thanks @josephfrazier for this hot fix
