### ISSUE TITLE
How to communicate features?

### ISSUE THREAD

**Issue by stefanbuck** [OctoLinker/browser-extension#209]
I have the feeling that a lot of features are not well explained to the users. For example did you know that the linking also works in Pull request? There is a list in the readme which outlines roughly what kind of languages and files are supported, but that's not enough. 

Do you have an idea of how we could do this? I was thinking about videos / images and gifs, but they aren't easy to maintain. Any suggestions are swarml welcome.

**Comment by stefanbuck** [comment]
What about adding a short animation to visualize the link replacement. On the settings page the user can turn off/on this hint.

![](https://cloud.githubusercontent.com/assets/1393946/20439120/74bed740-adba-11e6-826b-98eebd69b395.gif)

**Comment by dasilvacontin** [comment]
I think ideally you shouldn't need to communicate the features. It should just work wherever you'd expect it to work. Knowing the premise, ie 'click to navigate through any import', should suffice.

**Comment by stefanbuck** [comment]
I agree with you @dasilvacontin, but since we don't have full coverage for all languages and every single reference it can be confusing. I think the dot is a good midway solution.

**Comment by dasilvacontin** [comment]
Fair enough. I'll let you know if it ever conflicts with some other extension.
