### ISSUE TITLE
[Firefox] "Open link in new tab" has been blocked by Firefox pop-up blocker.

### ISSUE THREAD

**Issue by gluons** [OctoLinker/browser-extension#225]
[4.6.0](https://github.com/OctoLinker/browser-extension/releases/tag/4.6.0) has `Open link in new tab` option. After I use this option, I see this issue.

Using on **Firefox Beta** version **51.0b6 (64-bit)**.

![34](https://cloud.githubusercontent.com/assets/4688092/20995166/c93f51b0-bd27-11e6-90c5-62c1123ee220.png)

**Comment by stefanbuck** [comment]
Thanks for reporting. That's a bit tricky, because the extension needs to guess / fetch the url first before I can call the `window.open` function. Firefox treats this as a regular popup. I'm not sure if this is even possible without a bigger refactoring. In the meantime the only workaround is to enable pop-ups for github.com.

**Comment by gluons** [comment]
> I'm not add-ons developer. Sorry if I can't help you so much.

Is it posible to use [`tabs.create()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create)?

**Comment by stefanbuck** [comment]
Ohh nice, this looks promising. Thanks for the hint

**Comment by gluons** [comment]
It seems like [4.7.0](https://github.com/OctoLinker/browser-extension/releases/tag/4.7.0) hasn't been released on AMO, right?

![octolinker add ons for firefox](https://cloud.githubusercontent.com/assets/4688092/21342173/38c5970c-c6c3-11e6-88e8-9f1eb51596d5.png)

**Comment by stefanbuck** [comment]
I know 😞  They blocked the last update, because the GA tracking especially getting `analytics.js` from a remote server didn't meet the requirements. I'm working on a solution already. Sorry, I should have communicated it earlier.

**Comment by gluons** [comment]
🆗
🕐 ▶️ 🆕 🆙✔️  😃

:bowing_woman: :bowing_woman: :bowing_woman:

**Comment by josephfrazier** [comment]
Hi @gluons, [version 4.7.1](https://github.com/OctoLinker/browser-extension/releases/tag/v4.7.1) has been released and it is now available on AMO: https://addons.mozilla.org/en-US/firefox/addon/octolinker/

**Comment by gluons** [comment]
@josephfrazier Oh! Thank you very much for informing me. It works very well. Love it ❤️
