### ISSUE TITLE
Can't resolve "import" link to index.js

### ISSUE THREAD

**Issue by azemoh** [OctoLinker/browser-extension#231]
Should resolve `import "/folder/folder"` link to `"/folder/folder/index.js"`.
This works for `require`.

**Comment by stefanbuck** [comment]
A path with a leading slash means that this path is absolute. For example `/Users/foo/Desktop/test.js` is an absolute path. In a regular project you will never define your path like this. Anyway, the OctoLinker loading behaviour is aligned with the JS implementation. 

![screen shot 2016-12-19 at 23 10 00](https://cloud.githubusercontent.com/assets/1393946/21330978/81e99fce-c640-11e6-9f8d-d0692ccbdd39.png)

Can you point me to the repo where require with a leading slash is working? Sounds like this the bug 😉
