### ISSUE TITLE
Support html imports

### ISSUE THREAD

**Issue by tunnckoCore** [OctoLinker/browser-extension#233]
a la WebComponents?

```html
<link rel="import" href="x-app.html">
```

**Comment by stefanbuck** [comment]
I would love to implement it, but it's not that easy and I think even impossible. How do I know where the linked file is located? There is no schema like in NodeJS project to follow. Maybe you have something in mind?!

**Comment by tunnckoCore** [comment]
Hm. Don't know. But why how, it will be in the same directory where the file is. I mean, I think it can be the same why how you resolve relative require/import paths.

**Comment by tunnckoCore** [comment]
Hm. So, okey, I think I can try to do something :)

```
highlight-text-html-basic
highlight-text-html-twig
highlight-text-html-slim
highlight-text-html-vue
highlight-text-html-js // => ejs, and probably others
highlight-text-html-handlebars // => hbs, handlebars, htmlbars
highlight-text-html-erb
highlight-text-jade // => jade, pug
```
that's the classes, file extensions are many haha

**Comment by stefanbuck** [comment]
> it will be in the same directory where the file is

I wasn't aware of that. As you already mention the [lib/resolver/relative-file.js](https://github.com/OctoLinker/browser-extension/blob/master/lib/resolver/relative-file.js) is be able to link the files. Maybe you have to tweak the `relative-file` resolver slightly. If you open a work in progress PR, I can help you and give you early feedback.
