### ISSUE TITLE
Support `jsnext:main` and `module` in package.json

### ISSUE THREAD

**Issue by tunnckoCore** [OctoLinker/browser-extension#235]
I believe simple they can be added here [lib/plugins/npm-manifest/index.js#L34-L44](https://github.com/OctoLinker/browser-extension/blob/c2ceab4373a7d297bf2b52fc72dafde57276df66/lib/plugins/npm-manifest/index.js#L34-L44).

Or at least, one of them. I believe [`jsnext:main`](https://github.com/rollup/rollup/wiki/jsnext:main) was suggested by Rollup creator. But `module` would become "standard" one day - if I'm not in mistake it already can be seen `<script type="module">` in some places.

**Comment by josephfrazier** [comment]
Thanks for the suggestion! As you've noticed, it should be pretty straightforward to implement. Would you like to try it? [CONTRIBUTING.md](https://github.com/OctoLinker/browser-extension/blob/master/CONTRIBUTING.md) has a development guide, and I'd be happy to help with any issues you encounter.

For reference, here are some previous pull requests that have changes very similar to the ones that are required here:

* https://github.com/OctoLinker/browser-extension/pull/126
* https://github.com/OctoLinker/browser-extension/pull/127
* https://github.com/OctoLinker/browser-extension/pull/204

PS: There shouldn't be any problem with linking both `jsnext:main` and `module` fields.

**Comment by tunnckoCore** [comment]
thanks for the links
