### ISSUE TITLE
Stopped working in last week or so

### ISSUE THREAD

**Issue by tunnckoCore** [OctoLinker/browser-extension#245]
Just stopped. Tried to remove it and re-add it, but no. Tried to restart the browser and etc.

If this helps

![2017-01-02-16 59 22_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/21591431/7ba44f2a-d10c-11e6-8e46-7d004b2ff313.png)
![2017-01-02-16 58 13_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/21591432/7ba5a640-d10c-11e6-8e60-0d22b809a3f7.png)

**Comment by josephfrazier** [comment]
Are you sure this is caused by the extension? I just disabled it, loaded https://github.com/start-runner/start-preset/blob/master/lib/index.js, and saw the same errors. In my case, uBlock is preventing github.com from collecting _its_ analytics. I confirmed this by turning off uBlock on that url, reloading, and seeing no errors.

**Comment by tunnckoCore** [comment]
I'm not sure. And not sure about that exact errors. But it was working before week. Didn't add any new extensions or anything. I was always with all of these extensions for last year or so.

And to be clear. It's not only on that repo. It not works anywhere - other repos, readmes, issues - nowhere.

**Comment by josephfrazier** [comment]
Hmm, that is odd. Are you also able to reproduce the issue in Firefox? An easy way to launch Firefox with the extension loaded is `npm run firefox-open` from the root of the repository.

Thanks for the clarification about all urls being broken. I just tested the `start-runner` one to be sure that my setup is closer to yours.

**Comment by tunnckoCore** [comment]
> An easy way to launch Firefox with the extension loaded is npm run firefox-open from the root of the repository.

nah, i even didn't have firefox on the machine :D but yea installed it and the extension is working when run firefox-open

**Comment by josephfrazier** [comment]
Judging by the filenames in [the second screenshot above](https://cloud.githubusercontent.com/assets/5038030/21591432/7ba5a640-d10c-11e6-8e60-0d22b809a3f7.png), I really think the errors are coming from github's scripts and are unrelated to this extension.

Nevertheless, if you can track down the commit that broke things for you, we might be able to figure out if something else is going on. `git bisect` can help you with finding the commit in question. Here's a guide on how to use it: https://stackoverflow.com/questions/4713088/how-to-use-git-bisect/4714297#4714297

**Comment by tunnckoCore** [comment]
Omg ;d how I will know what break the things, when the extension is always auto updated - first. And second, I'm pretty busy and don't think that some user can know better than the creator/maintainer. It's not user job to investigate so deep.

And I said that i'm not sure for the pics. It is possible these errors to be there always. But I didn't change anything in the browser side (exts and etc) nor the OS (archlinux). Chrome Version 53.0.2785.116 (64-bit)

**Comment by josephfrazier** [comment]
Ok, let me back up for a minute. Are you sure the extension is actually broken? After taking a closer look at the aforementioned [screenshot](https://cloud.githubusercontent.com/assets/5038030/21591432/7ba5a640-d10c-11e6-8e60-0d22b809a3f7.png), it seems that the links are being detected and inserted, since the pink dots appear on the left side of the lines that the links are on.

If you visit that page again, do you still see the dots? If so, can you describe in detail what actions you are taking, what you expect to happen, and what is actually happening instead? Unfortunately, since no one else has been able to reproduce this issue, it's very difficult to debug without additional effort from you.

Let me know if you have any questions, thanks!

**Comment by tunnckoCore** [comment]
Yea it is broken. And yes there still are pink dots, but when click on the link it not works - just the "Processing" tooltip. It is expected to move me to the homepage of the package, if Ctrl + Click it should open it in new tab.

**Comment by josephfrazier** [comment]
Thanks for the clarification, that makes things easier to diagnose. If you go to https://github.com/start-runner/start-preset/blob/99acad86a67888eb4d92237370aa347b390fcc6f/lib/index.js#L1 and click on `'start'`, it shows the `Processing  ⏳` tooltip, but never actually redirects you to https://github.com/start-runner/start?

If so, it sounds like your machine may not be able to contact the [service](https://github.com/OctoLinker/live-resolver) that is used to determine the package homepage. Can you try loading https://githublinker.herokuapp.com/q/npm/start and tell me what happens?

Also, do relative filenames like this one work? https://github.com/OctoLinker/browser-extension/blob/706be13d7d9fd29e61c2f6f6fe421e3372fec3bc/lib/app.js#L2

**Comment by tunnckoCore** [comment]
> but never actually redirects you to

yep

> may not be able to contact the service  ... and tell me what happens?

```json
{"url":"https://github.com/start-runner/start"}
```

> Also, do relative filenames like this one work?

no

**Comment by tunnckoCore** [comment]
updated to latest chrome stable version

![2017-01-09-23 43 24_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/21784610/0d13845e-d6c5-11e6-8e38-4d072b9aae10.png)

extension removed and again added:

```
Additional Information
Version: 4.7.1
Updated: December 28, 2016
```

**Comment by josephfrazier** [comment]
Thanks for the additional info. It's good to see that https://githublinker.herokuapp.com is working, at least. Can you find a previous version of the extension that does work correctly? They are the `chrome-octolinker-X.Y.Z.zip` files listed on the [releases page](https://github.com/OctoLinker/browser-extension/releases), and they can be unzipped and loaded into Chrome as described here: https://developer.chrome.com/extensions/getstarted#unpacked

**Comment by tunnckoCore** [comment]
Yep, just seen you comment and was doing exactly this. It seems 4.7.0 works.

```
 4.7.0
 c2ceab4
```

**Comment by tunnckoCore** [comment]
Also just noticed that the options page is empty (just github btns star), but in 4.6.0 there was few options listed like "debug mode", "open url in new tab by default" and etc.

**Comment by josephfrazier** [comment]
> Also just noticed that the options page is empty (just github btns star)

That doesn't sound right at all. Every option from 4.6.0 should still be present in 4.7.1. Are you sure you haven't made any changes to the extension source code?

Since the `firefox-open` script worked for you earlier, I wonder if a similar `chrome-open` script also would. Could you check out the code in https://github.com/OctoLinker/browser-extension/pull/247 into a fresh directory, then run the following and see whether it's still broken?

```shell
npm install
npm run chrome-open
```

**Comment by tunnckoCore** [comment]
yea i'll try later, but it also is not shown in the official latest browser extension from the store

**Comment by stefanbuck** [comment]
Maybe you have two OctoLinker instance running (local + from the store) in your Chrome. Please ensure that only one version of OctoLinker is enabled.

**Comment by tunnckoCore** [comment]
Nope nope. I don't. I disabled it when started trying local things. I'm currently using local 4.7.0, until the problem is fixed.

**Comment by stefanbuck** [comment]
That's really strange. Do you see any errors in the background script console while using the extension? The console is available from the extensions page.

<img width="417" alt="screen shot 2017-01-11 at 11 16 37" src="https://cloud.githubusercontent.com/assets/1393946/21844591/86bbb22e-d7ef-11e6-8962-ad0ced810755.png">

**Comment by tunnckoCore** [comment]
i'll see later, maybe there should have smth

**Comment by stefanbuck** [comment]
Hi @tunnckoCore, can you check out the latest master and try it again. @josephfrazier did some refactoring in this area and maybe this solved the issue.

**Comment by stefanbuck** [comment]
@tunnckoCore any news from your side?

**Comment by tunnckoCore** [comment]
D'oh, i forgot that, i'll try in a bit.

**Comment by josephfrazier** [comment]
I'm closing this one due to inactivity. There doesn't seem to be much we can do here, especially given that @tunnckoCore is using the extension with a custom patch.
