### ISSUE TITLE
Unhandled promise rejection in storage.js

### ISSUE THREAD

**Issue by josephfrazier** [OctoLinker/browser-extension#248]
One of the Firefox extension reviewers left this comment about version 4.7.1:

> I'm getting an error with this add-on installed, since Firefox does not yet have chrome.storage.sync enabled. For the next version, can you make sure to fall back to chrome.storage.local if the sync methods reject the promise/throw an error?

> 18:02:55.092 Unhandled promise rejection Error: Please set webextensions.storage.sync.enabled to true in about:config

I haven't yet reproduced the problem myself, as I primarily use Chrome, but the relevant code appears to be on [lines 14 and 20 in storage.js](https://github.com/OctoLinker/browser-extension/blob/0db32d949b110152f3689fab183c534272c97efb/lib/options/storage.js#L14-L20). As suggested in the above comment, it should be pretty straightforward to add a more comprehensive fallback to `chrome.storage.local`.

We should probably also consider handling the case where `chrome.storage.local` fails as well (though I'm not sure if this happens in practice). Perhaps a `storage` API wrapper library would be helpful here.

**Comment by stefanbuck** [comment]
A wrapper around the storage sounds like a good idea :+1:

**Comment by josephfrazier** [comment]
I was able to reproduce the issue by running:

```shell
npm run firefox-open -- --firefox=firefoxdeveloperedition
```

and navigating to https://github.com/OctoLinker/browser-extension/blob/master/package.json

I'll keep looking into it.

**Comment by stefanbuck** [comment]
Another option would be to use [rfpify](https://www.npmjs.com/package/rfpify) to promisify the chrome extension api directly.

**Comment by josephfrazier** [comment]
`rfpify` looks pretty nifty, but the `chrome.storage` functions have an additional complication of putting their errors into `chrome.runtime.lastError`, so I'm hoping to find a wrapper than can properly deal with that. I've pushed up some work-in-progress to https://github.com/OctoLinker/browser-extension/pull/258
