### ISSUE TITLE
Object.entries is not a function

### ISSUE THREAD

**Issue by xovel** [OctoLinker/browser-extension#278]
OctoLinker cannot work already.

> Object.entries is not a function

**Browser name:**
QQBrowser

**Browser version:** 
v9.5.3
Chromium 53.0.2785.104

**OctoLinker version:** 
4.8.0

**URL and line number where issue occurs:** 

storage.js:39Uncaught (in promise) TypeError: Object.entries is not a function(…)

**Expected behavior:** 

**Actual behavior:**

**Comment by josephfrazier** [comment]
Hi @xovel, thanks for reporting the issue! I suspect this is related to the recent removal of `babel-polyfill` in https://github.com/OctoLinker/browser-extension/pull/258#issuecomment-275813737.

Are you able to update your browser to a more recent version? It looks like your current browser is a fork of an outdated version of Chromium, which may not support `Object.entries`. Furthermore, privacy and security issues have been discovered in QQ Browser, so I'd recommend switching to Chromium or Chrome if you can. See here for more info: https://citizenlab.org/2016/03/privacy-security-issues-qq-browser/

Whether or not you update your browser, it might be possible to fix this by reintroducing an `Object.entries` polyfill without causing errors about `Promise`. I'll leave this link here for reference: https://stackoverflow.com/questions/35090153/babel-support-for-object-entries

**Comment by xovel** [comment]
Thanks for your reply in this issue @josephfrazier . The version of my QQBrowser is currently newest.

`Object.entries` is a new `ES7` features and `Chromium 53` does not support it. Unfortunally, I've get used to use this browser in my work, change it to another maybe result in a series of problems. Anyway, I also use `Chrome 55.0.2883.75` in my computer, and `OctoLinker 4.8.0` work very well in this browser.

I try to roll the `OctoLinker`'s version to `4.6.0` in QQBrowser, and it worked again.
