### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by staabm** [OctoLinker/browser-extension#28]
would be great to get this great extension also in firefox

**Comment by petereberlecom** [comment]
:+1:

**Comment by stefanbuck** [comment]
See https://github.com/github-linker/chrome-extension/issues/29#issuecomment-74575088

**Comment by jdreesen** [comment]
+1

**Comment by mariusGundersen** [comment]
With the new WebExtension api in Firefox it should be pretty straight forward to make this an extension both in Chrome and Firefox. I'll see if I can help you with that

**Comment by stefanbuck** [comment]
That would be great @mariusGundersen

**Comment by stefanbuck** [comment]
Hi @mariusGundersen @jdreesen @petereberlecom @staabm

after a while I managed to get the Firefox version working. The PR is still open, because I have to fix some tests first. I'll announce it next week on Twitter, but you can already install it https://addons.mozilla.org/en-US/addon/octolinker/.

Please let me know if you have any questions or issues.

**Comment by xenithorb** [comment]
I hate doing +1's but here it is. I don't believe people actually pay attention to the "reaction emojis"

**Comment by xenithorb** [comment]
So here's the thing guys. You're familiar that 48+ supports WebExtensions. 

The extension in its current state seems to work ok with: https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/

I don't know the functionality that well but I was able to click on a few things in some code in this very repository and it took me to what seemed like there right file.

**Comment by stefanbuck** [comment]
Cool project @xenithorb. I've installed the OctoLinker from the Chrome Store in Firefox 55, but the extension wasn't working.

Anyway, I do pay attention to feature requests. In the last weeks I was working on the Firefox port which is almost done. A first version of the extension is already available in the firefox store and by end of this week the final version should be available there as well.

**Comment by stefanbuck** [comment]
Done https://addons.mozilla.org/en-US/firefox/addon/octolinker/

**Comment by xenithorb** [comment]
Thanks!

**Comment by stefanbuck** [comment]
You're welcome. It took a while since I had to wait for Firefox 46 which added WebExtension support.
