### ISSUE TITLE
[Feature Request] .vimrc NeoBundle support

### ISSUE THREAD

**Issue by davidosomething** [OctoLinker/browser-extension#31]
The syntax is typically
NeoBundle(Lazy)? 'GITHUBUSER/REPONAME'

e.g.
`NeoBundle 'haya14busa/incsearch.vim'`
Should link to [https://github.com/haya14busa/incsearch.vim](https://github.com/haya14busa/incsearch.vim)

match patterns are, on any .vimrc .gvimrc *.vim

(((Neo)?Bundle(Lazy|Fetch)?)|Plug(in)?)\s'(.)'

**Comment by stefanbuck** [comment]
Sorry out of scope for now. But feel free to send a PR to https://github.com/github-linker/core

**Comment by kwakayama** [comment]
:+1: for this feature
