### ISSUE TITLE
Don't show the update notifications

### ISSUE THREAD

**Issue by bfred-it** [OctoLinker/browser-extension#310]
**Browser name:** 

Chrome

**Browser version:** 

57

**OctoLinker version:** 

4.9.0

**Expected behavior:** 

Please stop notifying me that OctoLinker has updated.
My browser doesn't bug me, the extensions shouldn't either.

**Comment by stefanbuck** [comment]
Isn't it nice to know what we added to OctoLinker?

We also communicate new features on Twitter [@OctoLinker](https://twitter.com/octolinker). Compared to our active users (more than 12.000) we have less than 100 followers on Twitter. Therefore I added long time ago the notification to reach a broader audience.

Anyway, we can add an option to disable the notification.

**Comment by bfred-it** [comment]
Yes and no. I appreciate any updates but I don't really go read the release notes of every version of every software I manually or automatically update. There's a lot of notification noise already

An option would be nice

**Comment by bfred-it** [comment]
<3
