### ISSUE TITLE
JavaScript Dynamic Imports

### ISSUE THREAD

**Issue by thejameskyle** [OctoLinker/browser-extension#315]
**OctoLinker version:**  4.9.0

JavaScript is adding [dynamic imports](https://github.com/tc39/proposal-dynamic-import) which look like this:

```js
import("./module") // >> Promise<Module>
```

OctoLinker [doesn't appear to support these](https://github.com/thejameskyle/react-loadable-example/blob/f5b245574ce6a7901a7a6e739b45fc8bf80f98a1/src/components/App.js#L8) yet, it would be nice if it did.

**Comment by josephfrazier** [comment]
This seems like it should be relatively straight-forward to implement, if anyone would like to. You'll need to change `require(\.resolve)?` to `( require(\.resolve)? | import )` [here](https://github.com/OctoLinker/browser-extension/blob/9fe6a165f418e153bc6e20964d26238548f89664/packages/helper-grammar-regex-collection/index.js#L14), then port some [valid](https://github.com/OctoLinker/browser-extension/blob/9fe6a165f418e153bc6e20964d26238548f89664/packages/helper-grammar-regex-collection/test.js#L70-L77) and [invalid](https://github.com/OctoLinker/browser-extension/blob/9fe6a165f418e153bc6e20964d26238548f89664/packages/helper-grammar-regex-collection/test.js#L85-L91) tests into the corresponding forms using the dynamic import syntax.

**Comment by jmcmahon443** [comment]
Hi, I am not sure how the CI works, but I forked and created a branch called Issue #315.
https://github.com/OctoLinker/browser-extension/pull/318
