### ISSUE TITLE
Incorrect linking in JS markdown codeblocks

### ISSUE THREAD

**Issue by MethodGrab** [OctoLinker/browser-extension#32]
The plugin is trying to resolve every string in JS markdown codeblocks as a module.

An example of this can be seen in the README for the [gulp-htmlbars](https://github.com/mattma/gulp-htmlbars#gulpfilejs) repo, the plugin is trying to resolve every string in the `gulpfile.js` codeblock as a module, even paths.

![image](https://cloud.githubusercontent.com/assets/2421069/6635623/fe19a998-c95f-11e4-87c6-adab25cb0ffb.png)

![image](https://cloud.githubusercontent.com/assets/2421069/6635598/ca76931c-c95f-11e4-9601-e202f61f69f7.png)

**Comment by stefanbuck** [comment]
Thanks for reporting this issue. At the moment the link detection is fuzzy and will be improved in the next major version. In the meantime I'll take a look on it.

**Comment by MethodGrab** [comment]
Thanks, it's not a major thing I just couldn't see an open issue for it so I thought it was worth raising one! :+1:

**Comment by stefanbuck** [comment]
Fixed in the latest version
