### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by walidsa3d** [OctoLinker/browser-extension#33]
It would be nice to add support for Python imports

**Comment by stefanbuck** [comment]
Could you provide an example? I'm not so familiar with that, sorry.

**Comment by walidsa3d** [comment]
like: import termcolor
all python packages are hosted in pypi like this https://pypi.python.org/pypi/termcolor, there you can find the link to the homepage (usually github).

**Comment by stefanbuck** [comment]
Api: http://pypi.python.org/pypi/<package_name>/json
