### ISSUE TITLE
Add `href` attribute to the inserted link

### ISSUE THREAD

**Issue by tunnckoCore** [OctoLinker/browser-extension#345]
Still don't like that I can just see what's the link, so it would be good to add `href` or at least `title` attribute the the inserted `a` created in `lib/insert-link.js`

https://github.com/OctoLinker/browser-extension/blob/master/lib/insert-link.js

**Comment by josephfrazier** [comment]
Hi @tunnckoCore, thanks for the suggestion! This idea has been pretty thoroughly discussed in https://github.com/OctoLinker/browser-extension/pull/87, so I'm going to close this issue in the interest of keeping discussion in one place. https://github.com/OctoLinker/browser-extension/issues/277 is also related. Feel free to chime in on either of those, especially if you'd like to implement it :)
