### ISSUE TITLE
Composer: doesn't work when repo has named differently than the package

### ISSUE THREAD

**Issue by fprochazka** [OctoLinker/browser-extension#36]
For example the `doctrine/orm` in https://github.com/Kdyby/Doctrine/blob/master/composer.json is not linked.

**Comment by stefanbuck** [comment]
Thanks for reporting. The issue is the new line after `nette/robot-loader`. Not sure how I can fix that at the moment. 

I'm thinking about doing a bigger refactoring of the core. This would be ideally less strict with the dom .. we will see :wink:

**Comment by stefanbuck** [comment]
Fixed in latest version

**Comment by fprochazka** [comment]
Thanks!
