### ISSUE TITLE
Missing links in golang.org/x/ imports

### ISSUE THREAD

**Issue by guneysus** [OctoLinker/browser-extension#372]
![image](https://user-images.githubusercontent.com/949232/28715976-6eef4246-73a3-11e7-81c9-218617ead61b.png)

Missing links in `golang.org/x` imports.

Example:

https://github.com/rs/xhandler#using-xmux

**Comment by rgroothuijsen** [comment]
Still unsure about one thing. Would it be better to have the links pointing to the original documentation as they do now if you went to a golang.org package URL, or to have the links pointing to the Github mirrors where the actual code is located?

**Comment by rgroothuijsen** [comment]
Small question: right now, the golang.org/x/ and golang.org/pkg/ URLs point to documentation pages for those packages. Would it be more helpful to have them redirect to the actual source code or keep the link to the documentation page?

**Comment by stefanbuck** [comment]
That's just my personal view, but I think that pointing to the documentation is more useful. In most cases documentation pages are easier to access than raw source code and documentation is all what you need. We do the same for other languages like nodejs where we link core pages to the official documentation. I'm happy to discuss this further if you have strong feelings for your proposal.

**Comment by rgroothuijsen** [comment]
Oh, not at all, I thought there was merit in both approaches so I was doubting which one to go for. If it's consistent with how other languages are handled, that's a plus. In that case, the original paths can be used without any special parsing and it's just a matter of adding golang.org to the list of allowed domains.

**Comment by stefanbuck** [comment]
If you'd like to tackle this one, I would be happy to help with assistance (if needed). It will be fairly straightforward 😉

**Comment by stefanbuck** [comment]
Fixed as part of #381 and will be shipped later this week
