### ISSUE TITLE
[Feature request] HTML script relative path linking

### ISSUE THREAD

**Issue by sumanmaity112** [OctoLinker/browser-extension#382]
**Browser name:** Chrome

**Browser version:** 61.0.3163.100 (Official Build) (64-bit)

**OctoLinker version:**  4.12.0

**URL and line number where issue occurs:** N/A

**Expected behaviour:** OctoLinker does not or unable to link HTML script's **src** tag, like
`<script src="../components/temp/script.js"></script>`. You can see example [here](https://github.com/sumanmaity112/juice/blob/master/HTML/juicePiChart.html). Here you should be to click on `<script src="./js/juicePiChart.js"></script>` and see the file.

**Actual behaviour:** N/A

**Comment by deecewan** [comment]
I'll take a crack at this.
