### ISSUE TITLE
Tooltip glitch

### ISSUE THREAD

**Issue by ZaninAndrea** [OctoLinker/browser-extension#384]
**Browser name:** Chrome

**Browser version:** 61.0.3163.100 

**OctoLinker version:** 4.12.0

**URL and line number where issue occurs:** 
For example:
https://github.com/ZaninAndrea/mdeditor/blob/master/package.json
line 48

But really any file any line

**Expected behavior:** I enabled the option open in a new tab enabled, when I click a link it opens in a new tab and if I go back to the page and hover the link I clicked nothing should happen

**Actual behavior:** When going back to the page and hovering the link the tooltip "redirecting" is shown

Little glitch that doesn't harm usability, still thought it was worth sending an issue.

**Comment by stefanbuck** [comment]
Thanks for reporting this. I'll have a look at it soon
