### ISSUE TITLE
Permalink toolbar doesn't line up with selected line

### ISSUE THREAD

**Issue by bfred-it** [OctoLinker/browser-extension#391]
The permalink toolbar doesn't show up on the line you select, but rather about 2 lines above it. 

1. Visit https://github.com/OctoLinker/browser-extension/blob/master/.babelrc
2. Click on line 1
3. See issue:

Originally posted in https://github.com/sindresorhus/refined-github/issues/786

**Browser name:** 

Chrome

**Browser version:** 

62

**OctoLinker version:** 

4.13.0

**URL and line number where issue occurs:** 

No console error

**Expected behavior:** 

<img width="332" alt="expected" src="https://user-images.githubusercontent.com/1402241/32503098-544569b0-c417-11e7-8d40-d6f40c4b8a6d.png">

**Actual behavior:** 

<img width="297" alt="error" src="https://user-images.githubusercontent.com/1402241/32503103-56624218-c417-11e7-80dd-99900428e94b.png">

**Comment by stefanbuck** [comment]
Thanks for filling this issue. I had a quick look, but I couldn't found the reason why OctoLinker is repositioning the Permalink toolbar. Will have another look tomorrow. Do you have an idea?

**Comment by bfred-it** [comment]
https://github.com/OctoLinker/browser-extension/blob/3a5a798/lib/app.css#L35
