### ISSUE TITLE
External links are no longer working, getting http 500 error from website

### ISSUE THREAD

**Issue by xt0rted** [OctoLinker/browser-extension#402]
**Browser name:** Chrome
**Browser version:** 62
**OctoLinker version:** 4.14.0
**Expected behavior:** Should load site for npm package
**Actual behavior:** Doesn't load site due to an http 500 error from `https://githublinker.herokuapp.com/q/npm/JSONPath`
**URL and line number where issue occurs:** 
  - Works https://github.com/OctoLinker/browser-extension/blob/6107e955c040a4ca6e6a79f49f619d27b8ec8bf3/package.json#L7
  - Doesn't work https://github.com/OctoLinker/browser-extension/blob/6107e955c040a4ca6e6a79f49f619d27b8ec8bf3/package.json#L24

**Comment by stefanbuck** [comment]
Thanks for reporting. There was an issue with newrelic again. I disabled it for now which solved the issue.
