### ISSUE TITLE
Support for Vim plugins

### ISSUE THREAD

**Issue by evanrelf** [OctoLinker/browser-extension#41]
Vim plugin managers make you list out your plugins like this, with the tail end of GitHub URLs:

```vim
Plug 'terryma/vim-multiple-cursors'
Plug 'terryma/vim-expand-region'
Plug 'junegunn/vim-easy-align'
```

You can see more examples of this in my Vim configuration file: https://github.com/evanrelf/dotfiles/blob/master/nvimrc#L26

It would be awesome if this browser extension could make the part in the single quotes a link, like it does for NPM packages and the like.

**Comment by dasilvacontin** [comment]
+1

**Comment by dasilvacontin** [comment]
Awesome, thanks!
