### ISSUE TITLE
Support for rubygems

### ISSUE THREAD

**Issue by stefanbuck** [OctoLinker/browser-extension#42]
E.g.: https://github.com/jekyll/jekyll/blob/master/Gemfile

FYI @rayshan @thoroc @soberstadt

**Comment by stefanbuck** [comment]
https://twitter.com/Octo_Linker/status/718220067184492546

**Comment by stefanbuck** [comment]
rubygems support landed in the latest version see https://github.com/OctoLinker/browser-extension/releases

**Comment by rayshan** [comment]
:tada:
