### ISSUE TITLE
Support for Ruby

### ISSUE THREAD

**Issue by stefanbuck** [OctoLinker/browser-extension#43]
```ruby
require 'file'
require_relative
```

http://ruby-doc.org/core-2.2.3/Kernel.html#method-i-require

**Comment by lfender6445** [comment]
:+1:

**Comment by naveed-ahmad** [comment]
+1

**Comment by stefanbuck** [comment]
**UPDATE** :smiley: 

https://twitter.com/Octo_Linker/status/718220067184492546

[![][tweet]](https://twitter.com/Octo_Linker/status/718220067184492546)
[tweet]: https://cloud.githubusercontent.com/assets/1393946/14370051/9e6b2c42-fd2a-11e5-8428-0b0dec2e2a86.png

**Comment by stefanbuck** [comment]
ruby support landed in the latest version see https://github.com/OctoLinker/browser-extension/releases
