### ISSUE TITLE
use https url in github project

### ISSUE THREAD

**Issue by benatkin** [OctoLinker/browser-extension#430]
I noticed the URL in the metadata for this github project is plain http. GitHub pages has HTTPS support now. https://octolinker.github.io/

Without HTTPS someone with control of the router could direct people to a malicious URL to download it. Might be far-fetched but it's part of why the drive to switch to HTTPS is so intense!

**Comment by benatkin** [comment]
Also the twitter account links to the plain ol' HTTP URL.

**Comment by josephfrazier** [comment]
Good eye, @benatkin! I just changed the metadata, but @stefanbuck will have to change the twitter account profile text.

**Comment by stefanbuck** [comment]
Done. Thanks for reporting @benatkin :+1:
