### ISSUE TITLE
Support for Docker

### ISSUE THREAD

**Issue by Gerhut** [OctoLinker/browser-extension#62]
```Dockerfile
FROM nodejs:latest
```

https://docs.docker.com/engine/reference/builder/#from

[Docket Hub](https://hub.docker.com/) page would be OK

**Comment by stefanbuck** [comment]
Good idea :+1: As soon as the refactoring is completed (see dev branch), it should be quite easy to implement.

**Comment by stefanbuck** [comment]
Will be part of the next release
