### ISSUE TITLE
Support TypeScript reference tag

### ISSUE THREAD

**Issue by stefanbuck** [OctoLinker/browser-extension#67]
## Example
`<reference path="Validation.ts" />`

## Spec
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#1111-source-files-dependencies

**Comment by jamestalmage** [comment]
Also, require statements in `.ts` files should just work.

https://github.com/unional/ava/blob/master/index.d.ts#L1

**Comment by stefanbuck** [comment]
Added TypeScript support in the latest version `v4.2.0`
