### ISSUE TITLE
Support for Homebrew formulae

### ISSUE THREAD

**Issue by josephfrazier** [OctoLinker/browser-extension#72]
Here's an example, from https://github.com/Homebrew/homebrew-core/blob/0fb28a127340e7be9851d2764ab3127ab4cd520a/Formula/sngrep.rb#L14-L16

```ruby
  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "openssl"
```

These lines should have the following links:

* [autoconf](https://github.com/Homebrew/homebrew-core/blob/0fb28a127340e7be9851d2764ab3127ab4cd520a/Formula/autoconf.rb)
* [automake](https://github.com/Homebrew/homebrew-core/blob/0fb28a127340e7be9851d2764ab3127ab4cd520a/Formula/automake.rb)
* [openssl](https://github.com/Homebrew/homebrew-core/blob/0fb28a127340e7be9851d2764ab3127ab4cd520a/Formula/openssl.rb)

Here's the `depends_on` documentation: http://www.rubydoc.info/github/Homebrew/brew/master/Formula#depends_on-class_method

---

Would you be open to a PR implementing this? I can take a shot at it, but I'd like to get any necessary feedback before diving into the code.

**Comment by stefanbuck** [comment]
Yes please :+1: If you don't mind this would also be ideal to verify the current state of documentation and easiness of the project. So pleas write down any issues that you have so we can improve it. That would be super helpful.

The [bower plugin](https://github.com/OctoLinker/browser-extension/blob/master/lib/plugins/bower-manifest/index.js) should be a good point to start for you. Please also check out https://github.com/OctoLinker/browser-extension/blob/master/CONTRIBUTING.md for a quick start.

If you have any questions, please ask. I'm flying back today so my response time is a bit slower than normal.
