### ISSUE TITLE
Link identifiers to declarations / assignments.

### ISSUE THREAD

**Issue by jamestalmage** [OctoLinker/browser-extension#77]
```js
function Foo() {};

Foo.prototype.bar = function () {};

var foo = new Foo(...);

// later in the file
foo.bar();
```

Linkify the `foo` part of `foo.bar` to the `var foo = ...` line.
Linkify the `bar` part of `foo.bar` to the `prototype.bar = ...` line.

Tern runs in the browser, and already accomplishes this. ([demo](http://ternjs.net/doc/demo/#simple))

**Comment by stefanbuck** [comment]
This feature would transform github.com into an IDE 🚀  This is out of scope for this project, sorry. If you find an extension like this please add it [here](https://github.com/stefanbuck/awesome-browser-extensions-for-github)

**Comment by jamestalmage** [comment]
I'm not proposing editor features, just additional links. Adding links to JS code on GitHub seems to be *exactly* the scope of this project.

**Comment by jamestalmage** [comment]
The Tern demo I linked to is indeed IDE like, but I'm just referring to the "jump to" shortcut they offer (`alt-.` I believe). We could use tern to gather the same sort info that editor is using for the jump to command, and use it to linkify.

**Comment by sindresorhus** [comment]
@jamestalmage Have you seen https://chrome.google.com/webstore/detail/sourcegraph-chrome-extens/dgjhfomjieaadpoljlnidmbgkdffpack?hl=en ? It's very useful. The service itself is cool too: https://sourcegraph.com

**Comment by sindresorhus** [comment]
Try hovering and clicking stuff here: https://sourcegraph.com/github.com/avajs/ava@master/-/blob/lib/test.js

**Comment by stefanbuck** [comment]
@jamestalmage I was aware that you were referring to the "jump to" functionality. I still think that this functionality is out of scope for the following reason. To provide this functionality in a proper way we need an AST representation of the current file + all linked files, dependencies, core modules ... I'm not saying that this is impossible, but definitely not easy to do. As @sindresorhus mention, there are already great tools available which allows you to do that.

**Comment by jamestalmage** [comment]
Sure. I wasn't aware of sourcegraph. I am trying it out now, but it doesn't seem to work very well on GitHub (I can't get it to work at all, actually). It also requires that you submit the repository to their service for server side processing. I want something that just works quickly.

> all linked files, dependencies, core modules

That seems less relevant to me than the current file. I mostly want to be able to see `foo = bar.baz`, and be able to quickly find the declaration for `bar`. That would be doable with some very basic AST tools. Tern adds support for being smart about (for example) linking `this.someFunc()` to the appropriate declaration on the prototype. Yes, linking to additional files would make it more robust, but (as you said) difficult. Still, I think the low hanging fruit (parsing just the current file) adds a ton of value, and would "just work" in a way sourcegraph doesn't.

**Comment by sindresorhus** [comment]
@jamestalmage Maybe open an issue on https://github.com/sindresorhus/module-requests, requesting it then?

**Comment by jamestalmage** [comment]
@sindresorhus - done

@stefanbuck - Can you add a license to the repo?
