### ISSUE TITLE
Can't resolve imports of a directory

### ISSUE THREAD

**Issue by jamestalmage** [OctoLinker/browser-extension#78]
Assuming the following directory structure:

```
index.js
foo/
  index.js
```

And in the root `index.js`, you've got:

```js
import foo from './foo';
```

It is unable to resolve it to `./foo/index.js`

**Comment by jamestalmage** [comment]
Hmm.

This might not be what's actually wrong:

- [These lines are broken](https://github.com/babel/babel/blob/master/packages/babel-traverse/src/index.js#L10-L13)
- [These lines are not](https://github.com/babel/babel/blob/master/packages/babel-traverse/src/index.js#L40-L42)

**Comment by stefanbuck** [comment]
Thanks for reporting. Looks like the [import regex](https://github.com/OctoLinker/browser-extension/blob/b0bdcd077016d0ddf828e28f61b1404583c47f0c/packages/helper-grammar-regex-collection/index.js#L3) needs some more tweaks. Would you like to create a PR?

**Comment by jamestalmage** [comment]
Technically, those are export declarations. Do you care about that distinction? Should a separate regex be created? If you want the separate regex, can you point me to where I would add a line to make use of the new one?

**Comment by stefanbuck** [comment]
Good shout (I just woke up 😉 ). Yes please, a new reges makes totally sense. 

Please, declare the new regex in the [helper-grammar-regex-collection](https://github.com/OctoLinker/browser-extension/blob/b0bdcd077016d0ddf828e28f61b1404583c47f0c/packages/helper-grammar-regex-collection/index.js#L3) and update the [tests](https://github.com/OctoLinker/browser-extension/blob/b0bdcd077016d0ddf828e28f61b1404583c47f0c/packages/helper-grammar-regex-collection/test.js) there. After that you can add the new regex to the [JavaScript plugin](https://github.com/OctoLinker/browser-extension/blob/b0bdcd077016d0ddf828e28f61b1404583c47f0c/lib/plugins/javascript/index.js#L12) (Note there are not tests available for plugins, yet)

If you have any problem please let me know.
Thank you.

**Comment by jamestalmage** [comment]
I'm having trouble getting the tests to run (I haven't modified any code yet).

```
$ git clone ...
$ cd browser-extension
$ npm install
$ npm test

START:
19 05 2016 02:08:29.267:INFO [framework.browserify]: bundle built
19 05 2016 02:08:29.291:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
19 05 2016 02:08:29.299:INFO [launcher]: Starting browser PhantomJS
19 05 2016 02:08:30.524:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket /#IvwOY7lKOl9VmxHmAAAA with id 50288284
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: 'null' is not an object (evaluating 'containerEl.insertAdjacentHTML')
  at /var/folders/2_/zg9h6_xd4r3_z7c07s0cn8mw0000gn/T/5e90eda6bb7076c1b25691025a9dbda9.browserify:171 <- lib/gh-interface.js:30:2

Finished in 0.282 secs / 0 secs

SUMMARY:
✔ 0 tests completed
```

**Comment by stefanbuck** [comment]
Ohhh, what a start for you, I'm so sorry. Travis is also failing (I didn't notice that). Will try to fix it asap.

**Comment by stefanbuck** [comment]
The problem is this native function `[insertAdjacentHTML](https://github.com/OctoLinker/browser-extension/blob/b0bdcd077016d0ddf828e28f61b1404583c47f0c/lib/gh-interface.js#L30)` which seems to be not available in PhantomJS.

**Comment by stefanbuck** [comment]
Fixed https://github.com/OctoLinker/browser-extension/pull/79 Sorry again for the trouble.
