### ISSUE TITLE
links are incorrect when using rootpath

### ISSUE THREAD

**Issue by saelfaer** [OctoLinker/browser-extension#84]
when using modules like [Rootpath](https://www.npmjs.com/package/rootpath) you import your own modules via a path relative to the root of your app instead of to the current file.

meaning, if I 
```
require('rootpath')();
var myModule = require('app/myModule');
``` 
it would go go into my site's app folder and find myModule there.
however octoLinker thinks i'm requireing the myModule from the npm module called 'app'
and redirects me to that github instead.

**Comment by stefanbuck** [comment]
Ohhh, that's a tricky one. Rootpath changes the default behaviour how requires statements are working in such a different way which makes it really difficult to deal with it in a clever way. At the same time it’s super edge-casey and rare used (according to the download stats). I’m open for discussions and ideas. What do you think, how should this work?

**Comment by stefanbuck** [comment]
@saelfaer what do you think about my feedback? Are you agree with me?

**Comment by saelfaer** [comment]
Yes you are absolutely right, I was not really demanding a solution merely noting that it does not work in certain occasions. Maybe just adding a disclaimer  would be enough to let users know that it does not work in that specific case.
