### ISSUE TITLE
Feedback on Contribution Process

### ISSUE THREAD

**Issue by josephfrazier** [OctoLinker/browser-extension#86]
(in response to https://github.com/OctoLinker/browser-extension/issues/72#issuecomment-219362198 and https://github.com/OctoLinker/browser-extension/pull/81#issuecomment-220519588)

Hey, I finally got around to collecting my thoughts on this. I hope they're helpful!

---

After searching around the codebase for a bit, it wasn't too hard to see how everything fit together. I ended up modeling the new `homebrew` plugin after the `gem` plugin, rather than the `bower` plugin you recommended, since the `gem` plugin was simpler. For future contributors, it might be nice to have a link in CONTRIBUTING.md or DEVELOPER.md (maybe combine the two?) to a "canonical" commit that shows an example of a plugin being added. I didn't think to look for one of these, and I'm sure it cost me a bit of time on understanding the architecture.

If I'm completely honest, though, the project feels a little over-engineered, from the perspective of someone who just started working on it. I'm guessing there's good reasons for why it's the way it is, but I'll go ahead and write out what I'm thinking anyway: It seems to me that adding a new pattern/resolver is a bit too complicated. As you can see, [the commit that added homebrew support](https://github.com/OctoLinker/browser-extension/commit/b6df755208eae0b98e55fdf533b647b5d7bd4f8e) ended up changing 4 files, whereas I feel like the project could have been architected to allow for something like this instead:

``` javascript
import relativeFile from './lib/resolver/relative-file.js'

const HOMEBREW = /(?:depends_on|conflicts_with) (['"][^'"\s]+['"])/g;

module.exports = {
  '*.rb': {
    // Using a RegExp as a property name is kinda sketchy, as it just gets
    // converted to its string representation. However, the module that imports
    // this could convert the string back into a RegExp
    HOMEBREW: function (path, matchResult) {
      // `path` is a string containing the path to the blob
      // `matchResult` is the return value of String.prototype.match
      const formulaName = matchResult[1]
      return relativeFile(path, formulaName + '.rb')
    },
    // Other patterns for .rb files go here
  },
  // Other filename patterns go here
};
```

I just wrote the above off the top of my head (and I'm running a bit low on sleep), so there might be some problems, but I hope it makes sense what I'm trying to get at. Let me know if I didn't explain enough, and I can fill in the blanks.

**Comment by stefanbuck** [comment]
Thank you so much for your very useful feedback 👍 

You said you were searching around to see how everything works together. How useful was the  [Overview](https://github.com/OctoLinker/browser-extension/blob/master/DEVELOPER.md#overview) document for you? Do you think it make sense to extend the document with more details? 

I know exactly what you mean with over-engineered. I spent many hours to think about the architecture. I aimed for keeping the code flexible, reusable and easy (more or less in this order 😉). Before, the extension based on jQuery selectors which wasn't that flexible and accurate. I agree with you that editing multiple files isn't ideal. 

Some areas can be improved quite easy. For example an autoloader could load and register all plugins from `/plugins`. The regex for a plugin can be already defined within the plugin, but there was a reason why I splitted this out. For example the `REQUIRE` regex is used for JavaScript and Ruby. At this time I was really confident that this will pay off. Today I'm not sure if this is the right way to go. Even if they have the same keyword they often have additional markup/behaviour. 

Last but not least the resolver. This part worries me the most. The plugin design is driven by the need of flexibility and reusability again. For example the [npm-manifest](https://github.com/OctoLinker/browser-extension/blob/master/lib/plugins/npm-manifest/index.js) plugin. The value of a dependency object can be almost everything. A semver range, a Git URL, a GitHub shorthand or a local path. The plugin have to detect what is written on the right side. This happens during the [parsing process](https://github.com/OctoLinker/browser-extension/blob/943e29528eefa13e840db9968826d89c37855bf9/lib/plugins/npm-manifest/index.js#L7-L14). At this point, I have all information that I need to determine which resolver should be use for this dependency. Let me think about an alternative solution. Are you available for code review?

Actions:
- [ ] Think about how to simplify the plugin architecture. 
- [ ] Example commit which show of a plugin being added.
- [ ] Merge `CONTRIBUTING.md` and `DEVELOPER.md`
- [ ] Implement autoloader which loads all plugin from  `/plugins`
- [ ] Define RegEx in every plugin

**Comment by josephfrazier** [comment]
You're welcome for the feedback! Thanks for encouraging me to provide it and being so concerned with making the project easy to contribute to.

After thinking about it for a bit, I realize that I was probably too harsh in criticizing the project architecture. I think a lot of my confusion was caused by:

1. Not inspecting the commit history before diving into the code
2. Trying to find variable definitions by `grep`ing the project for the variable name, rather than following the `import` statements

Taking care of these two items would probably make the plugin addition process pretty clear:

> - [ ] Example commit which show of a plugin being added.
> - [ ] Merge CONTRIBUTING.md and DEVELOPER.md

I'll try to put together a PR or two addressing these. The other actions you mention are definitely worth considering as well, but I'm no longer sure they're worth the effort. What do you think?

**Comment by stefanbuck** [comment]
All good, I was asking for feedback and you provide one 👍  

The way that you describe above is the common way to start quickly with a new project, I would say. A contributor doesn't want to spend  hours in reading documentation and code. He wants to get his PR done fast as possible in a practical way. I don't think your feedback was to harsh and I really want to improve this for other contributors.

Go ahead with combining the docs and feel free to make some tweaks there.

**Comment by Ibrahim-Islam** [comment]
Contributing document is referring to [older commit for loading plugins](https://github.com/OctoLinker/browser-extension/commit/2541a407c5916b7d99dc61375a56f94dfb5121f1) and currently it seems that is not required because `load-plugins.js` takes care of loading any plugins.

**Comment by stefanbuck** [comment]
Upps sorry, it's always hard to write and keep docs up to date. Thanks for reporting.

**Comment by stefanbuck** [comment]
We should keep this in mind and improve the documentation whenever possible. Since there is no concrete action in this issue, I'm gonna to close this issue.
