### ISSUE TITLE
Links in discussions.

### ISSUE THREAD

**Issue by jamestalmage** [OctoLinker/browser-extension#90]
It would be awesome if this also worked for code in discussions:

``` js
var ava = require('ava');
```

Also, at least for Node stuff, it would be awesome to also parse for stack traces elements that had identifiable packages:

```
  at foo.bar (/user/dev/project/node_modules/foo/index.js:3:4)
```

Specifically, our regex for stack traces would be something like: 

``` js
  const regex = /node_modules[\\\/]([a-zA-Z_\.0-9]+):(\d+):(\d+)/;
  let match = regex.exec(line);
  let path = match[1];
  let line = match[2];
  let column = match[3];
```

**Comment by stefanbuck** [comment]
Thanks for submitting your awesome ideas!

Linking import and require statements in discussions is theoretically possible, with some constraints. This would only work for packages, but not for files. Also the language needs to be defined in the markdown ```javascript ... in order to pick the right parser.

The second one should be relative straightforward to implement.

Are you willing to implement one of those features with my help?

**Comment by jamestalmage** [comment]
> Are you willing to implement one of those features with my help?

I am, just time constrained now. I don't anticipate getting to it soon. But it's on my "someday" list. I will post here before starting any work, so anybody else - feel free to start on it before then.

**Comment by stefanbuck** [comment]
@jamestalmage I just started to work on linking code in PR discussions.  Will be part of the next release, JTLYK 😉

**Comment by stefanbuck** [comment]
I just realised that we're talking about different discussions, I think. I'm talking about those kind of code blocks
![screen shot 2016-10-20 at 01 35 14](https://cloud.githubusercontent.com/assets/1393946/19541295/843a3726-9665-11e6-98ec-44bf17c5335a.png)

and you probably about code block within an issue, right?
![screen shot 2016-10-20 at 01 36 04](https://cloud.githubusercontent.com/assets/1393946/19541310/95ee5d08-9665-11e6-9990-c4901b8cf49e.png)

**Comment by stefanbuck** [comment]
@jamestalmage linking in discussions and md files is available since today https://github.com/OctoLinker/browser-extension/releases/tag/4.7.0
